services:

  db:
    container_name: mysql-8
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: minisite
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "9080:8080"

  smtp4dev:
    image: rnwood/smtp4dev:v3
    container_name: smtp4dev
    restart: always
    ports:
      - "9081:80"
      - "90:25"
      - "143:143"

  backend:
    container_name: minisite-api
    build: .
    restart: always
    depends_on:
      - db
      - smtp4dev
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/minisite
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_MAIL_HOST: smtp4dev
      SPRING_MAIL_PORT: 25
      JWT_SECRET: change-me-very-long-secret
      JWT_EXPIRATION_MS: 3600000
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - ./uploads:/app/uploads
